### PR TITLE
Creds for terraform cloud remote

### PR DESCRIPTION
**Pull request by jmahowald**
I wasn't able to figure another way to be able to use terraform cloud for remote states, nor could I figure out if there is a general environment variable name to use for the terraform cloud token.

### CODE REVIEW

**Comment by sudomateo** [comment]
This workflow is already covered in the examples here: https://github.com/hashicorp/terraform-github-actions/blob/master/examples/backends.md

**Comment by jmahowald** [comment]
Thanks,

I might suggest to actually have a link on the main page of the github repo.  When I wrote this the .  It isn't clear in [Terraform Cloud's remote docs](https://www.terraform.io/docs/backends/types/remote.html)  how to do that. Also, when I wrote this, the docs at https://www.terraform.io/docs/github-actions/common-tasks/backends.html were using the previous workflow style, so I picked something that mirrored that behavior.

**Comment by jmahowald** [comment]
Actually, I have a follow up @sudomateo .  I switched to use what was in that document, and init went through but it didn't seem to carry over to my plan.  I also set in my env  TF_API_TOKEN so that it's available to the plan.  Is there something else I should do when running plan to make the credentials available if I ran init in the same job?


```
Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.```

**Comment by iniinikoski** [comment]
I might have a similar issue than you @jmahowald  (even though my init does not even to through):

```# tf init -upgrade -backend-config="token=<my working TFE token>" -backend-config="organization=<ORG>" -backend-config="hostname=<HOST>"
Upgrading modules...
- aws_networking_test in ..

Error: Error accessing remote module registry

Failed to retrieve available versions for module "label" (../main.tf:20) from
dep.app.redbull.com: error looking up module versions: 401 Unauthorized.


Error: Error accessing remote module registry

Failed to retrieve available versions for module "label" (../main.tf:20) from
dep.app.redbull.com: error looking up module versions: 401 Unauthorized.```

Terraform core version 0.12.16 here. I also create a Hashicorp support case out of this as my work is currently blocked :/

**Comment by iniinikoski** [comment]
Also, originally this support was here by @lkysow : https://github.com/hashicorp/terraform-github-actions/pull/15 - but it was dropped off...

**Comment by sudomateo** [comment]
@jmahowald would you be able to provide the redacted Terraform files being used?

**Comment by sudomateo** [comment]
@iniinikoski it would be helpful to see how the `label` module is being called. The error by itself does not give all of the information without the actual code for context.

**Comment by iniinikoski** [comment]
@sudomateo sure. We just do this:

```
module "label" {
  source    = "<TFE_HOSTNAME>/<ORG>/label/terraform"
  version   = "0.4.0"
  namespace = var.host_project
  stage     = var.environment
  name      = "elasticsearch"
  delimiter = "-"

  tags = {
    "Project"     = var.project,
    "Environment" = var.environment,
    "Component"   = "elasticsearch",
    "Terraform"   = "true"
    "Region"      = data.aws_region.current.name
  }
}
```

**Comment by sudomateo** [comment]
@iniinikoski Thank you for providing that. After reading [this documentation](https://www.terraform.io/docs/cloud/registry/using.html), it seems that the only way to authenticate to modules within a private module registry at this time is by using the CLI credentials file. I'll work on adding the CLI credentials file back into the code.

That being said I'm a bit curious as to where GitHub Actions fits into your workflow if you already are using Terraform Cloud/Enterprise. Care to share some details there?

**Comment by iniinikoski** [comment]
@sudomateo sure. I plan to use the Actions to test & verify modules - everything else is covered by TFE and it's PR-checking. I've never given a thought on plumbing the module repositories also to TFE workspaces. Hmm...

**Comment by sudomateo** [comment]
> I plan to use the Actions to test & verify modules 

@iniinikoski For clarity, when you say this, do you mean you are testing and validating modules using `terraform fmt` and/or `terraform validate`?

Also I have a branch named `adding-cli-credentials-file` located [here](https://github.com/hashicorp/terraform-github-actions/tree/adding-cli-credentials-file) if you would like to test it in your workflow. I tested it myself but would like to see if this covers your use case before I merge and release.

**Comment by iniinikoski** [comment]
> @iniinikoski For clarity, when you say this, do you mean you are testing and validating modules using `terraform fmt` and/or `terraform validate`?
> 

Both yes - and I need to do the init in between :)

> Also I have a branch named `adding-cli-credentials-file` located [here](https://github.com/hashicorp/terraform-github-actions/tree/adding-cli-credentials-file) if you would like to test it in your workflow. I tested it myself but would like to see if this covers your use case before I merge and release.

Works like a charm, cool and thanks! :)

**Comment by sudomateo** [comment]
@iniinikoski Thank you for testing that. I released v0.6.3 to include this functionality. Also thank you for the details on your use case. I will discuss use cases like this internally to see if this is something we can begin to provide in Terraform Cloud/Enterprise.

**Comment by jmahowald** [comment]
Regarding why Github Actions and Terraform Cloud.  I am actually trying both out, wanting to ensure the dev team that doesn't touch terraform much can do so with there standard pipeline tools, while weighing the workflow improvements of Terraform Cloud.  But even if I don't use Terraform Cloud for the workflows, using the remote state is nice.  I wish it would be easier to create a new workspace and set the management to local. (I'm aware that I can create something for this with using the TFE provider, but I'm talking about a simple command/flag)

**Comment by iniinikoski** [comment]
> I wish it would be easier to create a new workspace and set the management to local. (I'm aware that I can create something for this with using the TFE provider, but I'm talking about a simple command/flag)

@jmahowald tfhelper (https://github.com/hashicorp-community/tf-helper) could help you here maybe, if the TFE provider does not...

**Pull request closed without merging**
