### PR TITLE
Added terraform plan -destroy and terraform destroy actions

### PR DESCRIPTION
**Pull request by lufussel**
Added plandestroy and destroy actions based on the existing plan and apply actions. The commands run `terraform plan -destroy` and `terraform destroy` respectively.

I have used these actions for the past week without issues.

The Terraform GitHub Actions reference pages will need an update to match (https://www.terraform.io/docs/github-actions/actions/index.html).

### CODE REVIEW

**Comment by daniyalj** [comment]
Any plans to merge this?

**Comment by twebber90** [comment]
Would love to see this get merged!

**Comment by tz-rsickora** [comment]
Same here, would love to see this merged!

**Comment by nikolay-bocharov** [comment]
it's very nice to have

**Comment by canelkatmis** [comment]
It was nice but the repo is refactored. And there are no codeowners care with PRs

**Comment by sudomateo** [comment]
@lufussel This will need to be refactored to abide by the new repository layout. Given this new layout, `terraform plan -destroy` is already able to be implemented via the `plan` subcommand.

**Comment by sudomateo** [comment]
Closing in favor of #143.

**Pull request closed without merging**
