### PR TITLE
Feat/add python curl

### PR DESCRIPTION
**Pull request by rdkls**

### CODE REVIEW

**Comment by sudomateo** [comment]
@rdkls What's the use case for python here?

**Comment by rdkls** [comment]
Using a module which needs it e.g. https://github.com/claranet/terraform-aws-lambda

acknowledge it may bloat but probably a decent argument for including it given its widespread usage?

**Comment by sudomateo** [comment]
I'm a little wary of including it especially since you can technically use a `local-exec` to install any needed software. I'm working on a rewrite of these actions and now you've given me an idea to allow a method to install custom software for use cases like this.

**Comment by rdkls** [comment]
ah thanks @sudomateo I might look at local-exec then;
be preferable for us to not use a fork too

**Comment by sudomateo** [comment]
No problem! I like your check for the `COMMENTS_URL` variable though. I'm still weighing the pros and cons of including Python in the image versus implementing a quick feature to add custom software via the `entrypoint.sh` script.

**Pull request closed without merging**
