### PR TITLE
Terraform validate sometimes needs a workspace

### PR DESCRIPTION
**Pull request by gloutsch**

### CODE REVIEW

**Comment by lkysow** [comment]
Thanks Gauthier, I'm happy to accept this but for my own knowledge, how does `terraform validate` use the workspace? Can you give me an example where `validate` fails because it's running in the wrong workspace? Thanks!

**Comment by lkysow** [comment]
I get this error when running `validate` on that config:
```
Error: null_resource.workspace_is_valid: : invalid or unknown key: terraform.workspace must be == $region_$env (myworkspace)
```

How is this line allowed:
```
  "terraform.workspace must be == $region_$env (${local.workspace})" = true
```

Am I missing something? Thanks!

**Comment by gloutsch** [comment]
hey,

sorry could you try with the following snippet ? (i changed the variables in `locals`)

```
provider "null" {
  version = "~> 1.0"
}

locals {
  workspace = "${var.ws}"
}

resource "null_resource" "workspace_is_valid" {
  count = "${terraform.workspace == local.workspace ? 0 : 1}"

  "terraform.workspace must be == $ws (${local.workspace})" = true
}
```

```
terraform workspace new myworkspace || terraform workspace select myworkspace
terraform validate -var ws=myworkspace
```

**Comment by lkysow** [comment]
Ahh I see how it works now. (https://github.com/hashicorp/terraform/issues/15469#issuecomment-343499242, https://www.linkedin.com/pulse/devops-how-do-assertion-test-terraform-template-jamie-nelson/)

Okay I'll need to update the docs and everything but I'll get it out as soon as I can.

Also FYI this doesn't work in terraform 0.12 anymore (at least in my testing).

**Comment by gloutsch** [comment]
ok, thank you :)

**Pull request merged**
