### PR TITLE
Add apply action

### PR DESCRIPTION
**Pull request by nikovirtala**
This is a request to add `apply` action to HashiCorp's Terraform GitHub Actions library or at least raise discussion about running Terraform in automation. 

I created this solution while exploring the GitHub Actions capabilities and from a pure interest to run Terraform in CI/CD type of automation, like the real Infrastructure as Code is supposed to.

The solution presented in this pull request is far from being complete, as it is currently supports only the fully automated workflow where plan and apply are executed sequentially without manual approval/promotion interaction between these two actions.

This limitation is mainly due to following two limitations on GitHub Actions and Terraform:

- GitHub Actions does not (natively) support sharing artefacts between workflows
- Terraform does not (natively) support storing plans in to remote storage

Nevertheless if you're interested to run Terraform in full automation you can use this action by extending the current [recommend workflow](https://www.terraform.io/docs/github-actions/getting-started/index.html) with following code:

```hcl
action "terraform-apply" {
  uses = "hashicorp/terraform-github-actions/apply@master"
  needs = ["terraform-plan"]
  secrets = ["GITHUB_TOKEN"]
  env = {
    TF_ACTION_WORKING_DIR = "."
    TF_ACTION_WORKSPACE = "default"
  }
}
```

I can also raise a request to update the documentation on https://www.terraform.io/docs/github-actions/ if we decide to move forward with my proposal.

### CODE REVIEW

**Comment by lkysow** [comment]
Hi Niko, thanks for the PR. I think it would be useful to have an apply action but I wouldn't explicitly encourage users to use it by default because it's a bit dangerous to have an auto-apply depending on the Terraform config.

Let me talk to the rest of the TF team to hear their thoughts.

**Comment by shawnmclean** [comment]
`apply` would be beneficial to us. We have `apply` running on master branch on circleci. This is essential in our case because we're spinning up resources with terraform and passing the output into serverless.

**Comment by bennycornelissen** [comment]
I have added an apply step in my personal fork of this repo as well (I just wasn't ready to create a PR yet). Adding an apply step is quite tricky, since there are quite a few things to consider: 

## What is the goal of the apply?
You can run `terraform apply` in a CI/CD pipeline for multiple reasons, which are all valid, but can be very different. The obvious use case would be "to deploy infrastructure". In that case you'll most likely run the apply step on the master branch only. But how would you check if changes in a PR will actually work? That's the use case I was implementing myself, as a means of automated validation of Terraform modules. My modules include example plans (as per HashiCorp best practices) which I can use in CI to validate the module. I will first check out the master branch, initialize the example plan, and apply it. Next I will switch back to the PR and run through `init`, `plan` and finally `apply`. After a successful run, the created infrastructure would be destroyed (to keep my AWS bill in check).

## What do we do when apply fails?
This mainly depends on why you are applying in the first place. If it is as part of a deployment, you may want to try rolling back. Or you may just want to report failure and call for manual intervention. But if you are applying for validation (as I described above), you will probably want to destroy whatever was created, and you'll want to do it as part of the pipeline because otherwise any local state will be lost. 

To be honest I'm not completely sold on how Github Actions deals with error-handling and callbacks, but given how it works today, we may have to create separate apply actions for the different use cases.

**Comment by andrew-waters** [comment]
IMO apply is perfectly valid to have here as an action - as long as it comes with some clear documentation on the dangers - which should be obvious.

In case it's useful to anyone, I use apply in tandem with the filtering actions (in this example, merges to master will be applied):

```
workflow "Apply" {
  resolves = "terraform-apply"
  on = "push"
}

action "branch-filter" {
  needs = "merged"
  uses = "actions/bin/filter@master"
  args = "branch master"
}

action "terraform-apply" {
  needs = "branch-filter"
  uses = "andrew-waters/actions/tf/apply@master"
  secrets = [
    "GITHUB_TOKEN",
    "TF_ACTION_TFE_TOKEN",
    "PROVIDER_CREDENTIALS",
  ]
  env = {
    TF_ACTION_WORKING_DIR = "."
    TF_ACTION_WORKSPACE = "default"
  }
}
```

Worth noting that the presence of `TF_ACTION_TFE_TOKEN` in `terraform-apply.secrets` also then stores the state which makes this ideal for CI/CD.

**Comment by lkysow** [comment]
Closed by #22. Thanks for your work niko.

For now, you can view the docs here: https://github.com/hashicorp/terraform-website/pull/804

The apply action works via a pull request merge event or via a push event. See docs for more details.

**Pull request closed without merging**
